name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Pull request events check out a merge commit, not the PR's HEAD
        # We need to specify the HEAD directly to enable auto-fixing commits
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.0.0
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
        
    - name: Install dependencies
      run: poetry install --with dev
      
    - name: Format with Black
      run: poetry run black openai-model-tracker/
      
    - name: Commit formatting changes if needed
      # Only commit changes on PRs
      if: github.event_name == 'pull_request'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Apply automated Black formatting"
        file_pattern: 'openai-model-tracker/*.py'
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
        commit_author: "GitHub Actions <actions@github.com>"
        # This action automatically detects if there are changes
      
    - name: Type check with MyPy
      run: poetry run mypy openai-model-tracker/
